### ISSUE TITLE
invalid character detected, retrying.

### ISSUE THREAD

**Issue by erengozaydin** [r0oth3x49/ghauri#43] opened 2023-02-17 18:13 UTC
How can I bypass this error. 

Thank you

[WARNING] invalid character detected, retrying.
[WARNING] it was not possible to extract query output length for the SQL query provided.
[WARNING] Ghauri detected an error during current user extraction ()

**Comment by r0oth3x49** [comment] 2023-02-20 04:54
This is not a bug rather it's a handle to when an invalid character is detected then it retries with 3 different methodology to extract the character, if fails all the times then it changes the payload for extraction and once all payloads are utilized then it stops the program with above information. So no fix for this you can debug things by your self by using --proxy switch, passing the burpsuite as proxy to see what's going on

**Closed** 2023-02-20 04:55 UTC
Labels: documentation
