### ISSUE TITLE
Unable to retrive database

### ISSUE THREAD

**Issue by Krafi1281** [r0oth3x49/ghauri#181] opened 2024-09-30 15:10 UTC
Ghauri couldn't determine the number if character(s) in length query                   [15:07:25] [WARNING] it was not possible to extract query output length for the SQL query provided.

Please do something for that. I often get it.

**Comment by 0xAkarii** [comment] 2024-10-02 14:25
I've the same issues here :
[DEBUG] Ghauri couldn't determine the number if character(s) in length query
[10:22:24] [WARNING] it was not possible to extract query output length for the SQL query provided.

**Comment by r0oth3x49** [comment] 2024-10-03 07:38
Duplicate of #182

**Closed** 2024-10-03 07:40 UTC
Labels: invalid, wontfix
