### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by idiotboxai** [r0oth3x49/ghauri#91] opened 2023-07-28 04:41 UTC
installation problem in Debian 12 

Here are steps which I followed :

(.venv) user@debian:~/Documents/Hacking tools/ghauri$ git clone https://github.com/r0oth3x49/ghauri.git
Cloning into 'ghauri'...
remote: Enumerating objects: 866, done.
remote: Counting objects: 100% (257/257), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 866 (delta 145), reused 162 (delta 131), pack-reused 609
Receiving objects: 100% (866/866), 345.05 KiB | 2.56 MiB/s, done.
Resolving deltas: 100% (640/640), done.
(.venv) user@debian:~/Documents/Hacking tools/ghauri$ python3 -m pip install --upgrade -r requirements.txt
Requirement already satisfied: tldextract in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (3.4.4)
Requirement already satisfied: colorama in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: requests in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (2.31.0)
Requirement already satisfied: chardet in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (5.1.0)
Requirement already satisfied: idna in ./.venv/lib/python3.11/site-packages (from tldextract->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: requests-file>=1.4 in ./.venv/lib/python3.11/site-packages (from tldextract->-r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: filelock>=3.0.8 in ./.venv/lib/python3.11/site-packages (from tldextract->-r requirements.txt (line 1)) (3.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.11/site-packages (from requests->-r requirements.txt (line 3)) (3.2.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.11/site-packages (from requests->-r requirements.txt (line 3)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.11/site-packages (from requests->-r requirements.txt (line 3)) (2023.7.22)
Requirement already satisfied: six in ./.venv/lib/python3.11/site-packages (from requests-file>=1.4->tldextract->-r requirements.txt (line 1)) (1.16.0)
(.venv) user@debian:~/Documents/Hacking tools/ghauri$  python3 setup.py install
running install
/home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing ghauri.egg-info/PKG-INFO
writing dependency_links to ghauri.egg-info/dependency_links.txt
writing entry points to ghauri.egg-info/entry_points.txt
writing requirements to ghauri.egg-info/requires.txt
writing top-level names to ghauri.egg-info/top_level.txt
reading manifest file 'ghauri.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'ghauri.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ghauri
creating build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/extract.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/request.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/tests.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/inject.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/ghauri.py -> build/bdist.linux-x86_64/egg/ghauri
creating build/bdist.linux-x86_64/egg/ghauri/scripts
copying build/lib/ghauri/scripts/ghauri.py -> build/bdist.linux-x86_64/egg/ghauri/scripts
copying build/lib/ghauri/scripts/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/scripts
copying build/lib/ghauri/__init__.py -> build/bdist.linux-x86_64/egg/ghauri
creating build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/payloads.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/colors.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/config.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/prettytable.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/utils.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/session.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/banner.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/lib.py -> build/bdist.linux-x86_64/egg/ghauri/common
creating build/bdist.linux-x86_64/egg/ghauri/logger
copying build/lib/ghauri/logger/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/logger
copying build/lib/ghauri/logger/colored_logger.py -> build/bdist.linux-x86_64/egg/ghauri/logger
creating build/bdist.linux-x86_64/egg/ghauri/dbms
copying build/lib/ghauri/dbms/fingerprint.py -> build/bdist.linux-x86_64/egg/ghauri/dbms
copying build/lib/ghauri/dbms/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/dbms
creating build/bdist.linux-x86_64/egg/ghauri/extractor
copying build/lib/ghauri/extractor/advance.py -> build/bdist.linux-x86_64/egg/ghauri/extractor
copying build/lib/ghauri/extractor/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/extractor
copying build/lib/ghauri/extractor/common.py -> build/bdist.linux-x86_64/egg/ghauri/extractor
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/extract.py to extract.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/request.py to request.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/tests.py to tests.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/inject.py to inject.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/ghauri.py to ghauri.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/scripts/ghauri.py to ghauri.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/scripts/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/payloads.py to payloads.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/colors.py to colors.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/config.py to config.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/prettytable.py to prettytable.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/utils.py to utils.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/session.py to session.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/banner.py to banner.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/lib.py to lib.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/logger/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/logger/colored_logger.py to colored_logger.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/dbms/fingerprint.py to fingerprint.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/dbms/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/extractor/advance.py to advance.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/extractor/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/extractor/common.py to common.cpython-311.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/ghauri-1.2.3-py3.11.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ghauri-1.2.3-py3.11.egg
removing '/home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages/ghauri-1.2.3-py3.11.egg' (and everything under it)
creating /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages/ghauri-1.2.3-py3.11.egg
Extracting ghauri-1.2.3-py3.11.egg to /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
ghauri 1.2.3 is already the active version in easy-install.pth
Installing ghauri script to /home/user/Documents/Hacking tools/ghauri/.venv/bin

Installed /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages/ghauri-1.2.3-py3.11.egg
Processing dependencies for ghauri==1.2.3
Searching for tldextract==3.4.4
Best match: tldextract 3.4.4
Adding tldextract 3.4.4 to easy-install.pth file
Installing tldextract script to /home/user/Documents/Hacking tools/ghauri/.venv/bin

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for requests==2.31.0
Best match: requests 2.31.0
Adding requests 2.31.0 to easy-install.pth file

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for colorama==0.4.6
Best match: colorama 0.4.6
Adding colorama 0.4.6 to easy-install.pth file

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for chardet==5.1.0
Best match: chardet 5.1.0
Adding chardet 5.1.0 to easy-install.pth file
Installing chardetect script to /home/user/Documents/Hacking tools/ghauri/.venv/bin

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for filelock==3.12.2
Best match: filelock 3.12.2
Adding filelock 3.12.2 to easy-install.pth file

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for requests-file==1.5.1
Best match: requests-file 1.5.1
Adding requests-file 1.5.1 to easy-install.pth file

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for idna==3.4
Best match: idna 3.4
Adding idna 3.4 to easy-install.pth file

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for certifi==2023.7.22
Best match: certifi 2023.7.22
Adding certifi 2023.7.22 to easy-install.pth file

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for urllib3==2.0.4
Best match: urllib3 2.0.4
Adding urllib3 2.0.4 to easy-install.pth file

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for charset-normalizer==3.2.0
Best match: charset-normalizer 3.2.0
Adding charset-normalizer 3.2.0 to easy-install.pth file
Installing normalizer script to /home/user/Documents/Hacking tools/ghauri/.venv/bin

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using /home/user/Documents/Hacking tools/ghauri/.venv/lib/python3.11/site-packages
Finished processing dependencies for ghauri==1.2.3
(.venv) user@debian:~/Documents/Hacking tools/ghauri$ python3 -m pip install -e 

Usage:   
  /home/user/Documents/Hacking tools/ghauri/.venv/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
  /home/user/Documents/Hacking tools/ghauri/.venv/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
  /home/user/Documents/Hacking tools/ghauri/.venv/bin/python3 -m pip install [options] [-e] <vcs project url> ...
  /home/user/Documents/Hacking tools/ghauri/.venv/bin/python3 -m pip install [options] [-e] <local project path> ...
  /home/user/Documents/Hacking tools/ghauri/.venv/bin/python3 -m pip install [options] <archive url/path> ...

-e option requires 1 argument
(.venv) user@debian:~/Documents/Hacking tools/ghauri$ python3 -m pip install -e .
Obtaining file:///home/user/Documents/Hacking%20tools/ghauri
  Preparing metadata (setup.py) ... done
Requirement already satisfied: chardet in ./.venv/lib/python3.11/site-packages (from ghauri==1.2.3) (5.1.0)
Requirement already satisfied: colorama in ./.venv/lib/python3.11/site-packages (from ghauri==1.2.3) (0.4.6)
Requirement already satisfied: requests in ./.venv/lib/python3.11/site-packages (from ghauri==1.2.3) (2.31.0)
Requirement already satisfied: tldextract in ./.venv/lib/python3.11/site-packages (from ghauri==1.2.3) (3.4.4)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.11/site-packages (from requests->ghauri==1.2.3) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.11/site-packages (from requests->ghauri==1.2.3) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.11/site-packages (from requests->ghauri==1.2.3) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.11/site-packages (from requests->ghauri==1.2.3) (2023.7.22)
Requirement already satisfied: requests-file>=1.4 in ./.venv/lib/python3.11/site-packages (from tldextract->ghauri==1.2.3) (1.5.1)
Requirement already satisfied: filelock>=3.0.8 in ./.venv/lib/python3.11/site-packages (from tldextract->ghauri==1.2.3) (3.12.2)
Requirement already satisfied: six in ./.venv/lib/python3.11/site-packages (from requests-file>=1.4->tldextract->ghauri==1.2.3) (1.16.0)
Installing collected packages: ghauri
  Attempting uninstall: ghauri
    Found existing installation: ghauri 1.2.3
    Uninstalling ghauri-1.2.3:
      Successfully uninstalled ghauri-1.2.3
  Running setup.py develop for ghauri
Successfully installed ghauri-1.2.3
(.venv) user@debian:~/Documents/Hacking tools/ghauri$ ghauri
bash: /home/user/Documents/Hacking tools/ghauri/.venv/bin/ghauri: cannot execute: required file not found
(.venv) user@debian:~/Documents/Hacking tools/ghauri$

**Comment by idiotboxai** [comment] 2023-07-28 04:47
Done installation after root privileges

**Comment by r0oth3x49** [comment] 2023-07-30 13:48
> Done installation after root privileges ;

So the problem is solved for you I guess? Should I close this issue

**Comment by idiotboxai** [comment] 2023-07-31 08:31
yes close it

**Closed** 2023-08-01 12:12 UTC
Labels: bug
