### ISSUE TITLE
Export dumped data to csv on abort

### ISSUE THREAD

**Issue by mastercho** [r0oth3x49/ghauri#92] opened 2023-08-08 12:57 UTC
When website starts to time out and you abort ghauri there no where to find dumped data.

**Describe the solution you'd like**
Everytime when dump is aborted must export data to csv just like sqlmap, currently no way to find output anywhere...

**Describe alternatives you've considered**
Sadly no alternatives available and you lose your time if site timeouts

**Additional context**
Send you screenshot on email when asking update for latest fix  for https://github.com/r0oth3x49/ghauri/issues/86 as issue still exist

**Comment by r0oth3x49** [comment] 2023-08-08 19:27
Will take a look

**Comment by r0oth3x49** [comment] 2023-08-08 19:27
Isn't this issue  dup of #90

**Comment by mastercho** [comment] 2023-08-08 19:29
> Isn't this issue dup of #90

similar but not, issue 90 is a different case, there we have CSV but won't export new CSV when redumps, but here issue is if site start time out and abort wont save CSV

**Comment by r0oth3x49** [comment] 2023-08-08 19:42
Right I will check both

**Comment by r0oth3x49** [comment] 2023-09-23 10:51
need more information on this issue to reproduce it properly and fix. i tried the same thing and ghauri dumps the output in csv as expected. what i did is started a dump of 3 columns and sent an abort using keyboard ctrl+c waited for ghauri to detect the abort and then press **e**  to end the dump and it correctly saved the data to csv.
![Capture](https://github.com/r0oth3x49/ghauri/assets/11024397/bf04fa60-3837-4338-b3b8-79d8c8c0d857)

**Comment by mastercho** [comment] 2023-09-23 14:18
> need more information on this issue to reproduce it properly and fix. i tried the same thing and ghauri dumps the output in csv as expected. what i did is started a dump of 3 columns and sent an abort using keyboard ctrl+c waited for ghauri to detect the abort and then press **e** to end the dump and it correctly saved the data to csv. ![Capture](https://user-images.githubusercontent.com/11024397/270102628-bf04fa60-3837-4338-b3b8-79d8c8c0d857.PNG)

On your screenshot seems there is no timeout before you abort, issue is when site timeouts and you abort, time out like in screenshot

 ![Capture](https://ci3.googleusercontent.com/proxy/MsJ5H-daEYqNhrlclqWIoFOIQON783ht2AVg8Ay78O-9A8AaMehm7YYE7JEgTuK4tmymaSBw3CprHyNGw6R35PvsoDgi5fQWYTTs=s0-d-e1-ft#https://i.gyazo.com/8cf236b5268255ed9932404f85190908.png)

**Comment by r0oth3x49** [comment] 2023-09-23 20:05
Will try with timeout value set to lowest

**Comment by r0oth3x49** [comment] 2023-09-24 02:04
this is not a bug but a handle to it if you provide the input as (q)uit that means tool is going to quit straightaway you should use (e)nd instead and quit will always quit at current phase without doing anything further. so closing this issue as won't fix.

**Closed by r0oth3x49** 2023-09-24 02:04 UTC
Labels: wontfix

**Comment by mastercho** [comment] 2023-09-24 02:10
@r0oth3x49 i tried to end but its just continue to time out on end so not helping at all

**Comment by r0oth3x49** [comment] 2023-09-24 02:32
did you tried using --timeout=300 or more high value the reason could be site not responding within time frame.

**Comment by mastercho** [comment] 2023-09-25 14:09
> did you tried using --timeout=300 or more high value the reason could be site not responding within time frame.

If starts to timeout and i cancel Ghauri this means site won't load anymore if i re-run with` --timeout=300` won't happen anything, you just don't read details on issues and don't like to fix issues...

**Comment by r0oth3x49** [comment] 2023-09-25 19:48
As I said if I can't reproduce I cannot fix, will check if anyone else faces the same issue.
