### ISSUE TITLE
Getting error every time while parsing raw request file

### ISSUE THREAD

**Issue by chawdamrunal** [r0oth3x49/ghauri#95] opened 2023-08-19 05:59 UTC
NOTE : I am using M1 Architecture.

[11:27:04] [INFO] parsing HTTP request from 'raw.txt'
Traceback (most recent call last):
  File "/opt/homebrew/bin/ghauri", line 33, in <module>
    sys.exit(load_entry_point('ghauri', 'console_scripts', 'ghauri')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrunalchawda/tools/ghauri/ghauri/scripts/ghauri.py", line 443, in main
    resp = ghauri.perform_injection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrunalchawda/tools/ghauri/ghauri/ghauri.py", line 161, in perform_injection
    url = req.url
          ^^^^^^^
  File "/Users/mrunalchawda/tools/ghauri/ghauri/common/utils.py", line 131, in url
    url = f"{self.protocol}://{self.host}"
             ^^^^^^^^^^^^^
  File "/Users/mrunalchawda/tools/ghauri/ghauri/common/utils.py", line 164, in protocol
    referer = self.headers.get("Referer")
              ^^^^^^^^^^^^
AttributeError: 'HTTPRequest' object has no attribute 'headers'

**Comment by mastercho** [comment] 2023-08-21 13:02
I think that's related to your python version, which version are you using?

**Comment by r0oth3x49** [comment] 2023-08-26 20:28
@chawdamrunal I cannot reproduce this. @mastercho might be right you should set the default Python version to 3 instead if 2.

**Comment by r0oth3x49** [comment] 2023-09-23 01:41
The issue must be resolved for you as I don't see any further comments, closing this issue.

**Closed by r0oth3x49** 2023-09-23 01:41 UTC
Labels: can't reproduce
